const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JURIS_DATA:data,COURTS:courts}=require('../assets/data.js');
const {normalize,search,externalQuery}=require('../assets/search.js');
assert.equal(normalize('SÚMULA — Negativação'),'sumula negativacao');
assert.equal(search(data,{query:'fraude bancaria'})[0].id,'stj-479');
assert.equal(search(data,{query:'Súmula 479'})[0].id,'stj-479');
assert.equal(search(data,{query:'SERASA'}).length,2);
assert.equal(search(data,{query:'plano de saúde',mode:'all'})[0].id,'stj-608');
assert.equal(search(data,{query:'fraude roubo',mode:'all'}).length,0);
assert.equal(search(data,{query:'fraude roubo',mode:'any'}).length,2);
assert.equal(search(data,{query:'pessoa jurídica',mode:'exact'})[0].id,'stj-481');
assert.equal(search(data,{query:'pessoa roubo',mode:'exact'}).length,0);
assert.equal(search(data,{query:'de e a'}).length,0);
assert.equal(search(data,{court:'TJSP'}).length,0);
assert.equal(search(data,{court:'STF',area:'Constitucional'}).length,1);
assert.equal(search(data,{area:'Consumidor'}).length,4);
assert.equal(search(data,{query:'<script>alert(1)</script>'}).length,0);
assert.equal(search(data,{sort:'newest'})[0].id,'stf-786');
assert.equal(search(data,{sort:'oldest'})[0].id,'stj-385');
assert.equal(search(data,{}).length,7);
assert.equal(courts.length,92);
assert.equal(new Set(courts.map(c=>c.id)).size,92);
assert.equal(new Set(data.map(d=>d.id)).size,data.length);
for(const d of data){assert.ok(courts.some(c=>c.id===d.court));assert.match(d.date,/^\d{4}-\d{2}-\d{2}$/);const u=new URL(d.source);assert.equal(u.protocol,'https:');assert.ok(u.hostname.endsWith('.jus.br'));assert.ok(d.summary&&d.reference&&d.organ&&d.sourceLabel);}
const q=externalQuery('fraude bancária',courts.find(c=>c.id==='TJSP'),'Consumidor');
assert.ok(q.includes('site:jus.br'));assert.ok(q.includes('Tribunal de Justiça São Paulo'));assert.ok(q.includes('fraude bancária'));assert.ok(q.includes('Direito Consumidor'));
const root=path.resolve(__dirname,'..');const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const [,file] of html.matchAll(/(?:src|href)="(assets\/[^"]+)"/g))assert.ok(fs.existsSync(path.join(root,file)),file);
console.log('Pesquisa, filtros, fontes e integridade: verificações aprovadas.');
